# Generated by Django 4.0.5 on 2022-07-16 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrecurso', models.CharField(max_length=255)),
                ('aula', models.CharField(max_length=5)),
                ('semestre', models.CharField(max_length=5)),
                ('no_horas', models.IntegerField()),
                ('modalidad', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('tipo', models.CharField(default='Principal', max_length=20)),
                ('predeterminada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('no_calle', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('predeterminada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombretutor', models.CharField(max_length=255)),
                ('apellidotutor', models.CharField(max_length=255)),
                ('titulo', models.CharField(max_length=5)),
                ('email', models.CharField(max_length=255)),
                ('predeterminada', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiante.curso')),
                ('direccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiante.direccion')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estudiante.tutor')),
            ],
        ),
    ]
